#! /bin/sh

GAP=5
PAD=50
PADD=15
#. "/home/elf/.cache/wal/color.sh"

#bspc config normal_border_color "#b9b9b9"
#bspc config active_border_color "#b9b9b9"
#bspc config focused_border_color "$#b9b9b9"
bspc config presel_feedback_color "#b9b9b9"

compton --config /home/vh/.config/.compton.conf &

/home/vh/.config/bspwm/autostart &

xrdb ~/.Xresources

bspc monitor -d I II III IV V VI VII

bspc config border_width         0
bspc config window_gap           $GAP
bspc config top_padding          $PADD
bspc config bottom_padding       $PAD
bspc config left_padding         $PADD
bspc config right_padding        $PADD

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config focus_follows_pointer true
